export type Priority = "critical" | "high" | "medium" | "low";
export type ChecklistStatus = "pending" | "done" | "skip";

export interface ChecklistItem {
  id: string;
  label: string;
  note?: string;
  priority: Priority;
  status: ChecklistStatus;
  autoGenerated?: boolean; // marked true when built from family profile
}

export interface ChecklistCategory {
  id: string;
  label: string;
  icon: string;
  color: string;
  items: ChecklistItem[];
}

// Auto-generated from:
//   destination = Rhodes, Greece
//   season     = Summer (July)
//   nights     = 5
//   members    = 1 adult woman + girls 13 & 10
//   dietary    = vegan / vegetarian
//   allergy    = dairy (milk)
//   interests  = K-Pop, Harry Potter, Astronomy, Grunge Fashion
//   avoids     = hikes, deep water, long walks
export const checklistData: ChecklistCategory[] = [
  {
    id: "documents",
    label: "Documents",
    icon: "FileText",
    color: "blue",
    items: [
      { id: "doc-1",  label: "דרכונים — לכולן (בתוקף 6+ חודשים)",          priority: "critical", status: "pending" },
      { id: "doc-2",  label: "צילום דרכונים שמור בענן",                       priority: "critical", status: "pending", note: "Google Drive / iCloud — גישה גם ללא אינטרנט" },
      { id: "doc-3",  label: "ביטוח נסיעות (כולל כיסוי אלרגיות)",            priority: "critical", status: "pending", note: "לוודא כיסוי ספציפי לאלרגיית חלב", autoGenerated: true },
      { id: "doc-4",  label: "אישור רפואי לאלרגיית חלב — אנגלית",           priority: "high",     status: "pending", autoGenerated: true, note: "שימושי במסעדות וברפואה דחופה" },
      { id: "doc-5",  label: "כרטיסי טיסה (מודפסים + דיגיטלי)",              priority: "critical", status: "pending" },
      { id: "doc-6",  label: "אישורי מלון",                                   priority: "high",     status: "pending" },
      { id: "doc-7",  label: "כרטיסי EpiPen / מרשמים — אנגלית",             priority: "high",     status: "pending", autoGenerated: true },
      { id: "doc-8",  label: "Emergency contacts רשומים בנייד",               priority: "high",     status: "pending" },
    ],
  },
  {
    id: "money",
    label: "Money",
    icon: "Wallet",
    color: "green",
    items: [
      { id: "mon-1", label: "אירו מזומן — €200 להתחלה",                       priority: "high",   status: "pending", note: "חלק מהדוכנים בעיר העתיקה לא מקבלים כרטיס" },
      { id: "mon-2", label: "כרטיס אשראי ללא עמלת המרה",                     priority: "high",   status: "pending" },
      { id: "mon-3", label: "הודעה לבנק על נסיעה לחו\"ל",                   priority: "high",   status: "pending" },
      { id: "mon-4", label: "אפליקציית תשלום (Revolut / Wise)",              priority: "medium", status: "pending", note: "חוסך עמלות בחו\"ל" },
      { id: "mon-5", label: "תקציב כיס נפרד לבנות — לקניות + K-Pop merch",   priority: "medium", status: "pending", autoGenerated: true, note: "נועם ומעיין — קניות עצמאיות" },
      { id: "mon-6", label: "קוד PIN של כרטיסים ידוע בעל פה",               priority: "high",   status: "pending" },
    ],
  },
  {
    id: "electronics",
    label: "Electronics",
    icon: "Smartphone",
    color: "purple",
    items: [
      { id: "ele-1", label: "מטעני USB-C לכולן (3 יח')",                     priority: "high",   status: "pending" },
      { id: "ele-2", label: "מתאם חשמל אירופאי (Type C/F)",                 priority: "critical", status: "pending" },
      { id: "ele-3", label: "Power bank (10,000+ mAh)",                      priority: "high",   status: "pending", note: "ימים ארוכים בחוץ — הסוללה תגמר" },
      { id: "ele-4", label: "אוזניות לכולן (לטיסה + K-Pop 🎵)",              priority: "medium", status: "pending", autoGenerated: true },
      { id: "ele-5", label: "מצלמה / GoPro — שקיעות ואסטרונומיה",           priority: "medium", status: "pending", autoGenerated: true, note: "לילות כוכבים ברודוס — שמי לילה נקיים" },
      { id: "ele-6", label: "כרטיס זיכרון ריק (64GB+)",                     priority: "medium", status: "pending" },
      { id: "ele-7", label: "eSIM / SIM יוון או רואמינג פעיל",              priority: "high",   status: "pending" },
      { id: "ele-8", label: "אפליקציות מורדות אופליין: מפות, Spotify",      priority: "medium", status: "pending", autoGenerated: true, note: "K-Pop playlist מורדת — לטיסה ולחוף" },
      { id: "ele-9", label: "Stargazing app — Star Walk / SkySafari",        priority: "low",    status: "pending", autoGenerated: true, note: "לאסטרונומיה בלילות רודוס" },
    ],
  },
  {
    id: "clothing",
    label: "Clothing",
    icon: "Shirt",
    color: "pink",
    items: [
      { id: "clo-1", label: "בגדי קיץ קלים — 5–6 ימים",                     priority: "high",   status: "pending" },
      { id: "clo-2", label: "נעלי הליכה נוחות (לא ספורט — בגלל העיר העתיקה)", priority: "high",   status: "pending", note: "מדרגות אבן + מרצפות — sandals עם תמיכה", autoGenerated: true },
      { id: "clo-3", label: "כובע / כובע שמש — חשוב ביולי",                 priority: "high",   status: "pending" },
      { id: "clo-4", label: "משקפי שמש לכולן",                               priority: "high",   status: "pending" },
      { id: "clo-5", label: "בגד ים (שוליים בחוף — לא שחייה עמוקה)",         priority: "medium", status: "pending", autoGenerated: true, note: "לישיבה בחוף, צילומים, קצת שחייה קרובה" },
      { id: "clo-6", label: "חולצת שרוולים / cardigan לערבות",              priority: "medium", status: "pending", note: "מסעדות ממוזגות + ערב יווני" },
      { id: "clo-7", label: "ביגוד Grunge / aesthetic — בגדי תצלום",        priority: "low",    status: "pending", autoGenerated: true, note: "לתצלומי עיר עתיקה — Harry Potter + Grunge vibes" },
      { id: "clo-8", label: "שמלה / outfit לשקיעת Meltemi Rooftop",         priority: "low",    status: "pending", autoGenerated: true },
    ],
  },
  {
    id: "beach",
    label: "Beach",
    icon: "Waves",
    color: "cyan",
    items: [
      { id: "bch-1", label: "קרם הגנה SPF 50+ — כמות גדולה",                priority: "critical", status: "pending", note: "יולי ברודוס — שמש חזקה מאוד" },
      { id: "bch-2", label: "מגבות חוף (2–3)",                              priority: "high",   status: "pending" },
      { id: "bch-3", label: "שקית ים אטומה למים",                           priority: "medium", status: "pending" },
      { id: "bch-4", label: "כסא / מחצלת חוף קלה",                         priority: "low",    status: "pending", note: "לישיבה נוחה ללא חוף עמוק" },
      { id: "bch-5", label: "משקפת שנורקל (לא מחייבת — שוליים בלבד)",      priority: "low",    status: "pending", autoGenerated: true, note: "הבנות אוהבות להסתכל — לא שחייה עמוקה" },
      { id: "bch-6", label: "אוזניות עמידות למים לחוף",                     priority: "low",    status: "pending", autoGenerated: true },
    ],
  },
  {
    id: "food",
    label: "Food",
    icon: "UtensilsCrossed",
    color: "orange",
    items: [
      { id: "fod-1", label: "חטיפים טבעוניים לטיסה",                        priority: "high",   status: "pending", autoGenerated: true, note: "אוכל בטיסה לא תמיד טבעוני" },
      { id: "fod-2", label: "לאשר מראש ארוחה טבעונית עם חברת הטיסה",       priority: "high",   status: "pending", autoGenerated: true },
      { id: "fod-3", label: "רשימת מסעדות טבעוניות ברודוס — מורדת",        priority: "medium", status: "pending", autoGenerated: true, note: "Pebbles Veggie Kitchen, Garden of Eden, Mama Sofia" },
      { id: "fod-4", label: "ביטוי ביוונית: 'Είμαι vegan' (אני טבעוני)",  priority: "medium", status: "pending", autoGenerated: true },
      { id: "fod-5", label: "חטיפי אנרגיה / ברים לבנות לבין הארוחות",     priority: "medium", status: "pending", autoGenerated: true },
      { id: "fod-6", label: "אישור: Oat milk זמין ב-Koykos Café",           priority: "low",    status: "pending", autoGenerated: true },
    ],
  },
  {
    id: "dairy-allergy",
    label: "Milk Allergy Safety",
    icon: "ShieldAlert",
    color: "red",
    items: [
      { id: "dal-1", label: "EpiPen / אנטי-היסטמין — כמות מספקת",          priority: "critical", status: "pending", autoGenerated: true },
      { id: "dal-2", label: "כרטיס אלרגיה ביוונית + אנגלית",               priority: "critical", status: "pending", autoGenerated: true, note: "\"Είμαι αλλεργικός στο γάλα\" — להדפיס ולהחזיק בארנק" },
      { id: "dal-3", label: "לבדוק כל מנה — גם רטבים, לחמניות, קינוחים",  priority: "critical", status: "pending", autoGenerated: true },
      { id: "dal-4", label: "לזהות: butter, cream, whey, casein בתפריטים", priority: "high",    status: "pending", autoGenerated: true, note: "מוסתר לעיתים תחת שמות לא ברורים" },
      { id: "dal-5", label: "מיקום בית חולים ברודוס שמור בנייד",            priority: "high",    status: "pending", autoGenerated: true, note: "General Hospital of Rhodes: +30 22410 80000" },
      { id: "dal-6", label: "אפליקציית תרגום מורדת — יוונית",              priority: "high",    status: "pending", autoGenerated: true },
      { id: "dal-7", label: "Oat milk / Almond milk אלטרנטיבות — לדרוש",   priority: "medium",  status: "pending", autoGenerated: true },
      { id: "dal-8", label: "לא להניח ש-\"vegan\" = dairy-free אוטומטית",  priority: "high",    status: "pending", autoGenerated: true, note: "לשאול כל פעם במפורש" },
    ],
  },
  {
    id: "kids",
    label: "Kids",
    icon: "Heart",
    color: "violet",
    items: [
      { id: "kid-1", label: "בנות יודעות מספר הנייד של אבא בעל פה",         priority: "critical", status: "pending", autoGenerated: true },
      { id: "kid-2", label: "נקודת מפגש מוסכמת אם מתפרדות",                priority: "critical", status: "pending", autoGenerated: true },
      { id: "kid-3", label: "כל אחת עם כרטיס חירום בארנק",                 priority: "high",    status: "pending", autoGenerated: true, note: "שם, טלפון אבא, אלרגיה לחלב" },
      { id: "kid-4", label: "K-Pop playlist מוכנה לטיסה (נועם + מעיין)",   priority: "medium",  status: "pending", autoGenerated: true },
      { id: "kid-5", label: "ספרים / Harry Potter לטיסה",                  priority: "low",     status: "pending", autoGenerated: true },
      { id: "kid-6", label: "Astronomy app מורדת לנועם (Star Walk)",        priority: "low",     status: "pending", autoGenerated: true },
      { id: "kid-7", label: "מטר/שניים — מגבלת הסכום לקניות לכל אחת",     priority: "medium",  status: "pending", autoGenerated: true, note: "Grunge merch, K-Pop photobooks — לתקצב מראש" },
      { id: "kid-8", label: "תרופות ילדים בסיסיות (חום, כאב ראש, בטן)",   priority: "high",    status: "pending" },
    ],
  },
  {
    id: "travel-day",
    label: "Travel Day",
    icon: "Plane",
    color: "slate",
    items: [
      { id: "trv-1", label: "יציאה מהבית — 3 שעות לפני המראה",             priority: "critical", status: "pending" },
      { id: "trv-2", label: "Check-in אונליין — 24 שעות לפני",              priority: "high",    status: "pending" },
      { id: "trv-3", label: "כבודה נמדדת — מכסה מוסכמת עם חברת הטיסה",   priority: "high",    status: "pending" },
      { id: "trv-4", label: "EpiPen בתיק יד (לא בכבודה!)",                 priority: "critical", status: "pending", autoGenerated: true },
      { id: "trv-5", label: "נוזלים — 100ml בשקית שקופה",                 priority: "high",    status: "pending" },
      { id: "trv-6", label: "אוכל לטיסה — טבעוני ממוכן",                  priority: "high",    status: "pending", autoGenerated: true },
      { id: "trv-7", label: "הגעה למלון: לבדוק אלרגיות ב-reception",       priority: "high",    status: "pending", autoGenerated: true },
      { id: "trv-8", label: "SIM / רואמינג — להפעיל בנמל תעופה",          priority: "medium",  status: "pending" },
      { id: "trv-9", label: "ביטוי ראשון ביוונית: Kalimera (בוקר טוב) 🌅", priority: "low",     status: "pending" },
    ],
  },
];

export const priorityMeta: Record<Priority, { label: string; color: string; bg: string }> = {
  critical: { label: "חובה",   color: "text-red-700",    bg: "bg-red-100"    },
  high:     { label: "חשוב",   color: "text-orange-700", bg: "bg-orange-100" },
  medium:   { label: "מומלץ",  color: "text-yellow-700", bg: "bg-yellow-100" },
  low:      { label: "אופציה", color: "text-slate-600",  bg: "bg-slate-100"  },
};

export const categoryColorMap: Record<string, { ring: string; header: string; dot: string }> = {
  blue:   { ring: "ring-blue-200",   header: "bg-blue-50",   dot: "bg-blue-500"   },
  green:  { ring: "ring-green-200",  header: "bg-green-50",  dot: "bg-green-500"  },
  purple: { ring: "ring-purple-200", header: "bg-purple-50", dot: "bg-purple-500" },
  pink:   { ring: "ring-pink-200",   header: "bg-pink-50",   dot: "bg-pink-500"   },
  cyan:   { ring: "ring-cyan-200",   header: "bg-cyan-50",   dot: "bg-cyan-500"   },
  orange: { ring: "ring-orange-200", header: "bg-orange-50", dot: "bg-orange-500" },
  red:    { ring: "ring-red-200",    header: "bg-red-50",    dot: "bg-red-500"    },
  violet: { ring: "ring-violet-200", header: "bg-violet-50", dot: "bg-violet-500" },
  slate:  { ring: "ring-slate-200",  header: "bg-slate-50",  dot: "bg-slate-500"  },
};
