"use client";

import { useEffect, useRef, useState } from "react";
import {
  checklistData,
  categoryColorMap,
  priorityMeta,
  type ChecklistCategory,
  type ChecklistItem,
  type ChecklistStatus,
  type Priority,
} from "@/data/checklist";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Checkbox } from "@/components/ui/checkbox";
import {
  FileText, Wallet, Smartphone, Shirt, Waves,
  UtensilsCrossed, ShieldAlert, Heart, Plane,
  Download, Save, RotateCcw, ChevronDown, ChevronUp,
  Sparkles, CheckCircle2, Circle, MinusCircle,
} from "lucide-react";

// ─── icons map ────────────────────────────────────────────────────────────────
const ICON_MAP: Record<string, React.ReactNode> = {
  FileText:       <FileText       className="h-4 w-4" />,
  Wallet:         <Wallet         className="h-4 w-4" />,
  Smartphone:     <Smartphone     className="h-4 w-4" />,
  Shirt:          <Shirt          className="h-4 w-4" />,
  Waves:          <Waves          className="h-4 w-4" />,
  UtensilsCrossed:<UtensilsCrossed className="h-4 w-4" />,
  ShieldAlert:    <ShieldAlert    className="h-4 w-4" />,
  Heart:          <Heart          className="h-4 w-4" />,
  Plane:          <Plane          className="h-4 w-4" />,
};

const STORAGE_KEY = "ftp-checklist-v1";

// ─── helpers ──────────────────────────────────────────────────────────────────
function loadFromStorage(): Record<string, ChecklistStatus> | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch { return null; }
}

function saveToStorage(map: Record<string, ChecklistStatus>) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(map));
}

function buildStatusMap(categories: ChecklistCategory[]): Record<string, ChecklistStatus> {
  const map: Record<string, ChecklistStatus> = {};
  for (const cat of categories)
    for (const item of cat.items)
      map[item.id] = item.status;
  return map;
}

// ─── Priority badge ───────────────────────────────────────────────────────────
function PriorityBadge({ priority }: { priority: Priority }) {
  const meta = priorityMeta[priority];
  return (
    <span className={`inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-bold ${meta.bg} ${meta.color} select-none`}>
      {meta.label}
    </span>
  );
}

// ─── Status cycle button ──────────────────────────────────────────────────────
function StatusIcon({ status }: { status: ChecklistStatus }) {
  if (status === "done") return <CheckCircle2 className="h-5 w-5 text-green-500 flex-shrink-0" />;
  if (status === "skip") return <MinusCircle  className="h-5 w-5 text-slate-400 flex-shrink-0" />;
  return <Circle className="h-5 w-5 text-slate-300 flex-shrink-0" />;
}

// ─── Single checklist item ────────────────────────────────────────────────────
function Item({
  item,
  status,
  onToggle,
}: {
  item: ChecklistItem;
  status: ChecklistStatus;
  onToggle: (id: string) => void;
}) {
  const isDone = status === "done";
  const isSkip = status === "skip";

  return (
    <li
      className={`group flex cursor-pointer items-start gap-3 rounded-lg px-3 py-2.5 transition-colors hover:bg-muted/60 print:hover:bg-transparent ${isDone ? "opacity-60" : ""}`}
      onClick={() => onToggle(item.id)}
      role="checkbox"
      aria-checked={isDone}
    >
      <div className="mt-0.5 flex-shrink-0">
        <StatusIcon status={status} />
      </div>

      <div className="min-w-0 flex-1">
        <div className="flex flex-wrap items-center gap-1.5">
          <span className={`text-sm font-medium leading-snug ${isDone || isSkip ? "line-through text-muted-foreground" : "text-foreground"}`}>
            {item.label}
          </span>
          <PriorityBadge priority={item.priority} />
          {item.autoGenerated && (
            <span className="inline-flex items-center gap-0.5 rounded-full bg-purple-100 px-1.5 py-0.5 text-[9px] font-semibold text-purple-700 print:hidden">
              <Sparkles className="h-2.5 w-2.5" />
              אוטו
            </span>
          )}
        </div>
        {item.note && (
          <p className={`mt-0.5 text-xs leading-snug ${isDone ? "text-muted-foreground/60" : "text-muted-foreground"}`}>
            {item.note}
          </p>
        )}
      </div>
    </li>
  );
}

// ─── Category card ────────────────────────────────────────────────────────────
function CategoryCard({
  cat,
  statusMap,
  onToggle,
  filter,
}: {
  cat: ChecklistCategory;
  statusMap: Record<string, ChecklistStatus>;
  onToggle: (id: string) => void;
  filter: Priority | "all";
}) {
  const [open, setOpen] = useState(true);
  const colors = categoryColorMap[cat.color];

  const visibleItems = filter === "all"
    ? cat.items
    : cat.items.filter((i) => i.priority === filter);

  const doneCount = visibleItems.filter((i) => statusMap[i.id] === "done").length;
  const total     = visibleItems.length;
  const allDone   = total > 0 && doneCount === total;

  if (visibleItems.length === 0) return null;

  return (
    <div className={`overflow-hidden rounded-xl border border-border ring-2 ${colors.ring} print:ring-1 print:break-inside-avoid`}>
      {/* header */}
      <button
        className={`flex w-full cursor-pointer items-center gap-3 px-4 py-3 ${colors.header} transition-colors hover:brightness-95 print:cursor-default`}
        onClick={() => setOpen((o) => !o)}
        aria-expanded={open}
      >
        <span className={`flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full ${colors.dot} bg-opacity-20 text-foreground`}>
          {ICON_MAP[cat.icon]}
        </span>
        <span className="font-bold">{cat.label}</span>
        <span className="text-xs text-muted-foreground">
          {doneCount}/{total}
        </span>
        {allDone && (
          <span className="ml-0 rounded-full bg-green-100 px-2 py-0.5 text-[10px] font-bold text-green-700">
            הושלם ✓
          </span>
        )}
        <span className="ml-auto print:hidden">
          {open ? <ChevronUp className="h-4 w-4 text-muted-foreground" /> : <ChevronDown className="h-4 w-4 text-muted-foreground" />}
        </span>
      </button>

      {/* mini progress */}
      <div className="h-1 w-full bg-muted">
        <div
          className="h-1 bg-green-400 transition-all duration-500"
          style={{ width: total > 0 ? `${(doneCount / total) * 100}%` : "0%" }}
        />
      </div>

      {/* items */}
      {open && (
        <ul className="divide-y divide-border/50 px-1 py-1 print:block">
          {visibleItems.map((item) => (
            <Item
              key={item.id}
              item={item}
              status={statusMap[item.id] ?? "pending"}
              onToggle={onToggle}
            />
          ))}
        </ul>
      )}
    </div>
  );
}

// ─── Main page ────────────────────────────────────────────────────────────────
export default function ChecklistPage() {
  const [statusMap, setStatusMap] = useState<Record<string, ChecklistStatus>>(() =>
    buildStatusMap(checklistData)
  );
  const [filter,     setFilter]     = useState<Priority | "all">("all");
  const [saved,      setSaved]      = useState(false);
  const [justSaved,  setJustSaved]  = useState(false);
  const didLoad = useRef(false);

  // hydrate from localStorage once
  useEffect(() => {
    if (didLoad.current) return;
    didLoad.current = true;
    const stored = loadFromStorage();
    if (stored) setStatusMap((prev) => ({ ...prev, ...stored }));
  }, []);

  // ── stats ──────────────────────────────────────────────────────────────────
  const allItems  = checklistData.flatMap((c) => c.items);
  const total     = allItems.length;
  const doneCount = allItems.filter((i) => (statusMap[i.id] ?? "pending") === "done").length;
  const skipCount = allItems.filter((i) => (statusMap[i.id] ?? "pending") === "skip").length;
  const pct       = total > 0 ? Math.round((doneCount / total) * 100) : 0;

  const criticalLeft = allItems.filter(
    (i) => i.priority === "critical" && (statusMap[i.id] ?? "pending") === "pending"
  ).length;

  // ── handlers ───────────────────────────────────────────────────────────────
  function toggleItem(id: string) {
    setStatusMap((prev) => {
      const cur = prev[id] ?? "pending";
      const next: ChecklistStatus =
        cur === "pending" ? "done" : cur === "done" ? "skip" : "pending";
      return { ...prev, [id]: next };
    });
    setSaved(false);
  }

  function handleSave() {
    saveToStorage(statusMap);
    setSaved(true);
    setJustSaved(true);
    setTimeout(() => setJustSaved(false), 2000);
  }

  function handleReset() {
    if (!confirm("לאפס את כל הרשימה?")) return;
    const fresh = buildStatusMap(checklistData);
    setStatusMap(fresh);
    localStorage.removeItem(STORAGE_KEY);
    setSaved(false);
  }

  function handlePrint() {
    window.print();
  }

  return (
    <>
      {/* ── print styles ─────────────────────────────────────────── */}
      <style>{`
        @media print {
          body { font-size: 11px; }
          .print\\:hidden { display: none !important; }
          .no-print { display: none !important; }
          header { display: none !important; }
          main { padding: 0 !important; max-width: 100% !important; }
          @page { margin: 1.5cm; }
        }
      `}</style>

      <div className="space-y-6">

        {/* ── Page header ───────────────────────────────────────────── */}
        <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <h1 className="text-xl font-black tracking-tight">Trip Preparation Checklist</h1>
            <p className="mt-0.5 text-sm text-muted-foreground">
              רודוס · יולי 2025 · 5 לילות · מותאם אישית לפרופיל המשפחה
            </p>
          </div>
          <div className="flex flex-wrap gap-2 print:hidden">
            <button
              onClick={handleSave}
              className="inline-flex cursor-pointer items-center gap-1.5 rounded-lg border border-border bg-background px-3 py-2 text-xs font-semibold text-foreground transition-colors hover:bg-muted"
            >
              <Save className="h-3.5 w-3.5" />
              {justSaved ? "נשמר ✓" : "שמור"}
            </button>
            <button
              onClick={handleReset}
              className="inline-flex cursor-pointer items-center gap-1.5 rounded-lg border border-border bg-background px-3 py-2 text-xs font-semibold text-muted-foreground transition-colors hover:bg-muted"
            >
              <RotateCcw className="h-3.5 w-3.5" />
              אפס
            </button>
            <button
              onClick={handlePrint}
              className="inline-flex cursor-pointer items-center gap-1.5 rounded-lg bg-foreground px-3 py-2 text-xs font-semibold text-background transition-opacity hover:opacity-90"
            >
              <Download className="h-3.5 w-3.5" />
              ייצא PDF
            </button>
          </div>
        </div>

        {/* ── Global progress card ───────────────────────────────────── */}
        <div className="rounded-xl border border-border bg-card p-5 shadow-sm">
          <div className="mb-3 flex items-end justify-between gap-2">
            <div>
              <span className="text-3xl font-black tabular-nums">{doneCount}</span>
              <span className="text-lg font-semibold text-muted-foreground"> / {total}</span>
              <span className="mr-2 text-sm text-muted-foreground">פריטים הושלמו</span>
            </div>
            <span
              className={`text-2xl font-black tabular-nums ${
                pct === 100 ? "text-green-500" : pct >= 70 ? "text-blue-500" : pct >= 40 ? "text-amber-500" : "text-red-500"
              }`}
            >
              {pct}%
            </span>
          </div>

          <Progress value={pct} className="h-3 rounded-full" />

          <div className="mt-3 flex flex-wrap gap-3 text-xs text-muted-foreground">
            <span className="flex items-center gap-1">
              <CheckCircle2 className="h-3.5 w-3.5 text-green-500" />
              {doneCount} הושלמו
            </span>
            <span className="flex items-center gap-1">
              <MinusCircle className="h-3.5 w-3.5 text-slate-400" />
              {skipCount} דולגו
            </span>
            <span className="flex items-center gap-1">
              <Circle className="h-3.5 w-3.5 text-slate-300" />
              {total - doneCount - skipCount} נשארו
            </span>
            {criticalLeft > 0 && (
              <span className="flex items-center gap-1 rounded-full bg-red-100 px-2 py-0.5 font-bold text-red-700">
                <ShieldAlert className="h-3 w-3" />
                {criticalLeft} פריטי חובה עוד פתוחים
              </span>
            )}
            {pct === 100 && (
              <span className="flex items-center gap-1 rounded-full bg-green-100 px-2 py-0.5 font-bold text-green-700">
                🎉 מוכנות לטיסה!
              </span>
            )}
          </div>

          {/* unsaved indicator */}
          {!saved && doneCount > 0 && (
            <p className="mt-2 text-[11px] text-amber-600 print:hidden">
              יש שינויים שלא נשמרו — לחצי על <strong>שמור</strong> לשמירה מקומית
            </p>
          )}
        </div>

        {/* ── Auto-generated note ────────────────────────────────────── */}
        <div className="flex items-start gap-2 rounded-lg border border-purple-200 bg-purple-50 p-3 text-xs text-purple-800 print:hidden">
          <Sparkles className="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-purple-500" />
          <span>
            <strong>הרשימה נוצרה אוטומטית</strong> לפי: יעד (רודוס), עונה (קיץ יולי), פרופיל משפחה (מבוגרת + 13 + 10), תזונה (טבעוני/צמחוני), אלרגיה (חלב), תחומי עניין (K-Pop, Harry Potter, אסטרונומיה).
            פריטים עם <span className="inline-flex items-center gap-0.5 rounded-full bg-purple-200 px-1.5 py-0.5 text-[9px] font-bold text-purple-800"><Sparkles className="h-2.5 w-2.5" />אוטו</span> הותאמו ספציפית לפרופיל.
          </span>
        </div>

        {/* ── Filter bar ─────────────────────────────────────────────── */}
        <div className="flex flex-wrap gap-2 print:hidden">
          {(["all", "critical", "high", "medium", "low"] as const).map((f) => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              className={`cursor-pointer rounded-full px-3 py-1.5 text-xs font-semibold transition-colors ${
                filter === f
                  ? "bg-foreground text-background"
                  : "border border-border bg-background text-muted-foreground hover:bg-muted"
              }`}
            >
              {f === "all"      ? "הכל"       :
               f === "critical" ? "חובה 🔴"   :
               f === "high"     ? "חשוב 🟠"   :
               f === "medium"   ? "מומלץ 🟡"  : "אופציה ⚪"}
            </button>
          ))}
        </div>

        {/* ── Legend ─────────────────────────────────────────────────── */}
        <div className="flex flex-wrap gap-4 text-xs text-muted-foreground print:hidden">
          <span className="flex items-center gap-1"><CheckCircle2 className="h-4 w-4 text-green-500" /> לחיצה ראשונה = הושלם</span>
          <span className="flex items-center gap-1"><MinusCircle  className="h-4 w-4 text-slate-400" /> לחיצה שנייה = דלוג</span>
          <span className="flex items-center gap-1"><Circle       className="h-4 w-4 text-slate-300" /> לחיצה שלישית = בטל</span>
        </div>

        {/* ── Categories grid ────────────────────────────────────────── */}
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          {checklistData.map((cat) => (
            <CategoryCard
              key={cat.id}
              cat={cat}
              statusMap={statusMap}
              onToggle={toggleItem}
              filter={filter}
            />
          ))}
        </div>

        {/* ── Print footer ───────────────────────────────────────────── */}
        <div className="hidden print:block mt-6 border-t pt-4 text-xs text-slate-500">
          <p>Family Travel Planner · רודוס יולי 2025 · הודפס {new Date().toLocaleDateString("he-IL")}</p>
          <p className="mt-1">הרשימה נוצרה אוטומטית לפי פרופיל המשפחה. לבדוק כל מנה לאלרגיית חלב.</p>
        </div>

      </div>
    </>
  );
}
